name: remote ssh command
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /${{ secrets.USERNAME }}
            PUBLIC_URL=/certsviewer bash ./deploy_project.sh ${{ github.event.repository.name }} certsviewer "npm install" "npm run build"